# Uncomment this file to enable multilanguage site support

[zh-cn]
contentDir="content/zh-cn"
languageName = "中文"
languagedirection = "ltr"
title = "之成的天窗"
weight = 2
[zh-cn.params]
subtitle = "永不止步"

[en]
contentDir="content/en"
languageName = "English"
languagedirection = "ltr"
title = "Zhicheng's sunroof"
weight = 1
