# Uncomment this file to enable multilanguage site support

[zh-cn]
contentDir="content/zh-cn"
languageName = "中文"
languagedirection = "ltr"
title = "之成的天窗"
weight = 1

[en]
contentDir="content/en"
languageName = "English"
languagedirection = "ltr"
title = "Zhicheng's Sunroof"
weight = 1
