# Configure main menu and social menu
# [[main]]
# identifier = "home"
# name = "Home"
# url = "/"
# [main.params]
# icon = "home"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/zhengfran"

[social.params]
icon = "brand-github"

[[social]]
identifier = "Run"
name = "Run"
url = "https://sunroof.zhengzhicheng.com/running_page/"

[social.params]
icon = "run"

[[social]]
identifier = "Email"
name = "email"
url = "mailto:zhicheng.ink98@gmail.com"

[social.params]
icon = "mail"
